---
title: Sevenwire
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    headline: 
    current: false
    featured: false
email: b@sevenwire.com
url: https://sevenwire.com
github_username: sevenwire
markdown: kramdown
plugins:
- jekyll-feed
