---
title: Sevenwire
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: "site"
email: b@sevenwire.com
url: https://sevenwire.com
github_username: sevenwire
markdown: kramdown
plugins:
- jekyll-feed
